# Use official Python base image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y gcc curl build-essential \
    && apt-get clean

# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy project files
COPY . .

# Collect static files (no-op if you're not using them)
RUN python manage.py collectstatic --noinput

# Start app with Gunicorn
CMD ["gunicorn", "shorty_project.wsgi:application", "--bind", "0.0.0.0:8000"]
